###
#Start First Job
POST http://localhost:8080/api/job/start/First Job
Content-Type: application/json

[
  {
    "paramKey": "city",
    "paramValue": "Kramatorsk"
  },
  {
    "paramKey": "state",
    "paramValue": "Ukraine"
  }
]

###
#Start Second Job
POST http://localhost:8080/api/job/start/Second Job

###
#Start Absent Job
POST http://localhost:8080/api/job/start/Fake Job