logging:
  level:
    net.shyshkin: debug
---
spring:
  config:
    activate:
      on-profile: mysql

  datasource:
    url: jdbc:mysql://localhost:23306/batch_db
    username: batch_user
    password: batch_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  batch:
    jdbc:
      platform: mysql
      initialize-schema: embedded

---
spring:
  config:
    activate:
      on-profile: multiple-datasource

  datasource:
    jdbc-url: jdbc:mysql://localhost:23306/batch_db
    username: batch_user
    password: batch_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  batch:
    jdbc:
      platform: mysql
      initialize-schema: embedded
  universitydatasource:
    jdbc-url: jdbc:mysql://localhost:33306/university_db
    username: university_user
    password: university_password
    driver-class-name: com.mysql.cj.jdbc.Driver

---
spring:
  config:
    activate:
      on-profile: external-api
app:
  external:
    students-api:
      url: http://localhost:8090/api/v1/


---
spring:
  config:
    activate:
      on-profile: external-api-list
app:
  external:
    students-api:
      url: http://localhost:8090/api/v1/


