version: '3'

services:
  mysql:
    image: mysql
    ports:
      - '23306:3306'
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_USER: batch_user
      MYSQL_PASSWORD: batch_password
      MYSQL_DATABASE: batch_db
    volumes:
      - mysql-data:/var/lib/mysql

  university-db:
    image: mysql
    ports:
      - '33306:3306'
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_USER: university_user
      MYSQL_PASSWORD: university_password
      MYSQL_DATABASE: university_db
    volumes:
      - university-data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

volumes:
  mysql-data:
  university-data: